### ISSUE TITLE
Prioritize Python's standard tomllib library for later versions

### ISSUE THREAD

**Issue by TheRealKeto** [jonpalmisc/emake#4]
Since the release of 3.11, Python officially supports parsing TOML files without the need of extra dependencies. I noticed that for all current versions of the project, the standard library is not used.

I'm happy to submit a PR that prioritizes the usage of the standard library for later versions of Python, just wanted to get an ok on this. Note that this proposal will not limit the project to a higher version that already assigned, as support for older versions can still be achieved with `tomli`.

**Comment by jonpalmisc** [comment]
Assuming that the API is the same, and `tomlib` can be imported as `tomli` when available (or vice versa), then that sounds like a fine change and a PR that I would accept.

**Comment by TheRealKeto** [comment]
I've gone ahead and opened a pull request. Are there any plans for a version bump when this change is accepted? If that's the case, the proposed PR can include the version bump.

**Comment by jonpalmisc** [comment]
Merged without bumping version as I'm not going to cut a new release for this right away—it will get lumped in with the next feature or bug fix release.

Thanks for your contribution!
